### PR TITLE
fix: Prevent unwanted disposal of fallback chunks and add sanity check

### LINKED ISSUE #538: 3D example constantly disposing chunk
When running the OME-Zarr v0.5 example with a maximized browser window on a 1080p monitor, the logger constantly logs the following messages

```
[2025-11-25T18:45:14.098Z][DEBUG][ChunkManager] Disposing chunk {"x":0,"y":0,"z":1,"c":0,"t":0} in LOD 3
logger.ts:126 [2025-11-25T18:45:14.098Z][DEBUG][ChunkManager] Disposing chunk {"x":0,"y":1,"z":1,"c":0,"t":0} in LOD 3
logger.ts:126 [2025-11-25T18:45:14.098Z][DEBUG][ChunkManager] Disposing chunk {"x":1,"y":0,"z":1,"c":0,"t":0} in LOD 3
logger.ts:126 [2025-11-25T18:45:14.098Z][DEBUG][ChunkManager] Disposing chunk {"x":1,"y":1,"z":1,"c":0,"t":0} in LOD 3
```

I think these are intended to be prefetched fallback chunks that are not visible (i.e. we start at z=0).

If that's true, I believe this bug may be incurring a decent amount of work by continuously disposing then fetching these chunks. Even if the fetch responses are cached, they still need to be decompressed.

I think this bug was introduced in #514, likely because that slightly changes the definition of what prefetch means.

### PR DESCRIPTION
**Pull request by aganders3**
### Summary
This is intended to fix #538, unwanted disposal of fallback chunks (not visible or prefetch, but assigned a priority) by disposing all chunks with null priority. This also adds a logic sanity check and will throw an error if any visible or prefetch chunks have null priority. See `chunk_store.ts`: 202-219.

### Related Issue
Closes #538

### Tests & Checks
Tested all examples, in particular the OME-Zarr v0.5 example that was exhibiting the bug

### CODE REVIEW

File: packages/core/src/core/chunk_store.ts [hunk 1]
```diff
@@ -209,13 +209,18 @@ export class ChunkStore {
     }
 
     const shouldDisposeChunk =
-      chunk.state === "loaded" && !chunk.visible && !chunk.prefetch;
+      chunk.state === "loaded" && chunk.priority === null;
     if (shouldDisposeChunk) {
```
Comment (andy-sweet) [inline packages/core/src/core/chunk_store.ts:213]: This has become small enough where inlining it improves readability.

```suggestion
if (chunk.state === "loaded" && chunk.priority === null) {
```

File: packages/core/src/core/chunk_store.ts [hunk 2]
```diff
@@ -209,13 +209,18 @@ export class ChunkStore {
...
+      if (chunk.visible || chunk.prefetch) {
+        throw new Error(
```
Comment (andy-sweet) [inline packages/core/src/core/chunk_store.ts:215]: I'm fine with this, though it makes me yearn for a true dev/debug assert in javascript.

**Review by andy-sweet — APPROVED** [review]
Thanks for separating this out! The disposal logic is much more clear to me now!

File: packages/core/src/core/chunk_store.ts (hunk 1 above)
Comment (andy-sweet) [reply packages/core/src/core/chunk_store.ts:213]: Oh, now I realize we have similar vars for the other conditions. Better to keep these consistent rather than change one. Ideally, I'd like to inline them all, but totally optional!
